-- ---------------------------------------------------------------------------
-- testlights.lua - ORO's lights-and-shadows test rig
--
-- An AUTOMATIC sequence of thirteen cases that exercises the patched client's
-- local-light work: spot shadow maps (one per light or per cluster, up to six),
-- the sticky selection when there are more lights than maps, the wide stadium
-- flood, point-light shadows (aimed map or five-face cube), spots ranking before
-- points, the sixteen-light budget, the day/night split, and the crowded pad's
-- capped floods. Every case says on
-- screen what it shows, what to expect, which Launchpad row it needs and what
-- the ORO lcl dbg log line should read. A full pass is about six and a half
-- minutes, so anyone can record it and send the video.
--
-- HOW TO RUN: the "Lights and shadows" scenario
-- (Scenarios\ORO\5 Night and lights) carries the line
--     Script testlights
-- in its environment block, so Orbiter runs this file as the scenario loads
-- (the LuaInline module must be ticked in the Launchpad's Modules tab). The
-- scenario holds ONE landed DeltaGlider (GL-01) on the flat ground at KSC, at
-- night; everything else (lamp posts, extra vessels) is spawned by this script
-- relative to the DG and deleted at the end. It can also be started from the Lua
-- console at any such scenario with run('testlights').
--
-- NOTE: THE RIG IS POSITION- AND HEADING-AGNOSTIC BY CONSTRUCTION, so moving the DG
-- needs no edit here: the reference lng/lat/heading are read from the vessel at
-- load (dgLng/dgLat/hdg0 below), every placement is given in VESSEL-FRAME metres
-- (right, forward) and converted by geo(), and the night jump is computed from
-- the load-time geometry. What the park DOES have to provide is clear, flat
-- ground: the rig's footprint is a 42 m radius ring plus two lamps out to ~72 m
-- ahead, and the cameras orbit the DG at about 50-80 m.
-- CURRENT PARK (2026-09-13, his): -80.6485750 / +28.5830320, heading 36, which
-- puts the VAB 331 m off the PORT beam (bearing 296.5 true, 55 m aft of abeam).
-- That is outside every lamp's reach - the spots are 250 m and aimed DOWN at the
-- DG, the posts are 120 m - so the VAB is a silhouette in the background here,
-- not a caster or a receiver in any case.
--
-- KEYS (Orbiter's own, no key hooks exist for a scenario script):
--     T       next case        (the "faster" key; the warp is put back to 1x at once)
--     R       previous case    (the "slower" key; same)
--     Ctrl+P  pause - the sequence freezes with the sim
--
-- SETTINGS for a full pass (Launchpad > Video > Advanced setup): Local lights 16x
-- Full, Spot light shadows 6 spot maps, Point light shadows Cube, Terrain and
-- world shadows Cascaded (ORO). Set ShadowDebug = 1 in D3D9Client.cfg when a run
-- is meant for a report: the client then logs "ORO lcl dbg:" once a second and
-- every case names the shape that line should have.
--
-- The lamp classes (Config\Vessels\ORO_LampSpot.cfg / ORO_LampPost.cfg and their
-- meshes) are generated by tools/lampgen.py in the ORO repo. Each lamp is its own
-- vessel with ONE emitter added here, so every other lamp is a caster in its map
-- (the client excludes only the emitter's own vessel).
-- ---------------------------------------------------------------------------

local RAD = math.pi / 180
local TAG = 'testlights: '

local function log(msg) oapi.write_log(TAG .. msg) end

-- ---------------------------------------------------------------------------
-- the client's settings, read from D3D9Client.cfg in the Orbiter root
-- ---------------------------------------------------------------------------
local LIGHTCFG = { [0] = '1 light', '4x Partial', '4x Full', '8x Partial', '8x Full',
                   '12x Partial', '12x Full', '16x Partial', '16x Full' }
local TERRSHD  = { [0] = 'Off', 'Stencil', 'Projected', 'Cascaded (ORO)' }
local PTMODE   = { [0] = 'Off', 'Aimed', 'Cube' }
local SELFSHD  = { [0] = 'None', 'Focus only', 'Focus + nearby', 'All' }

local cfg = {}
local cfgFound = false
do
  local f = io.open('D3D9Client.cfg', 'r')
  if f then
    cfgFound = true
    for line in f:lines() do
      local k, v = string.match(line, '^%s*([%w_]+)%s*=%s*(%S+)')
      if k then cfg[k] = v end
    end
    f:close()
  end
end
local function cfgnum(key, default)
  local v = tonumber(cfg[key])
  if v == nil then return default end
  return v
end
-- the client's own defaults for a cfg that predates the keys
local S = {
  lights   = cfgnum('LightConfiguration', 1),
  shadows  = cfgnum('LocalLightShadows', 1),
  maps     = cfgnum('LocalLightShadowMaps', 4),
  point    = cfgnum('LocalLightShadowPoint', 1),
  terrain  = cfgnum('TerrainShadowing', 1),
  selfshd  = cfgnum('ShadowMapMode', 0),
  debug    = cfgnum('ShadowDebug', 0),
}
if S.shadows == 0 then S.maps = 0 end
local maxLights = ({ [0] = 1, 4, 4, 8, 8, 12, 12, 16, 16 })[S.lights] or 4
local atlasName = (S.terrain == 3) and 'cascade atlas' or ((S.maps > 1) and 'local atlas' or 'scratch')

-- ---------------------------------------------------------------------------
-- the reference vessel and the local frame
-- ---------------------------------------------------------------------------
local dg = vessel.get_interface('GL-01')
if dg == nil then dg = vessel.get_focusinterface() end
if dg == nil then
  log('no GL-01 and no focus vessel - nothing to test against')
  return
end
local hDG = dg:get_handle()
local hEarth = oapi.get_objhandle('Earth')
local eq = dg:get_equpos()
local st = dg:get_status()
local dgLng, dgLat, R0 = eq.lng, eq.lat, eq.rad
local hdg0 = 0
if st.status == 1 then hdg0 = st.surf_hdg else log('WARNING: ' .. dg:get_name() .. ' is not landed - the rig assumes a parked vessel') end
local mjd0 = oapi.get_simmjd()
log(string.format('reference %s (%s) lng %.5f lat %.5f hdg %.1f', dg:get_name(), dg:get_classname(), dgLng / RAD, dgLat / RAD, hdg0 / RAD))

-- the sun's elevation at the DG, from the three global positions (no oapi horizon call needed)
local hSun = oapi.get_objhandle('Sun')
local function sunElev()
  local up = vec.unit(vec.sub(dg:get_globalpos(), oapi.get_globalpos(hEarth)))
  local toSun = vec.unit(vec.sub(oapi.get_globalpos(hSun), dg:get_globalpos()))
  return math.asin(vec.dotp(up, toSun))
end

-- the rig is a NIGHT test: if the scenario was loaded (or saved) in daylight, the clock
-- is advanced to two hours after the sun passes 8 deg below the horizon. The advance is
-- COMPUTED ONCE from the load-time geometry (latitude, the sun's declination and hour
-- angle, the planet's rotation period) and applied as ONE jump: the first flight's
-- per-frame search stepped the clock 25 h and never saw night, because the positions it
-- sampled did not follow the clock inside that first second. The day case jumps twelve
-- hours from whatever mjd0 ends up being.
local nightForced = false
local function forceNight()
  local e0 = sunElev()
  if e0 < -8 * RAD then return end
  local pE, pD = oapi.get_globalpos(hEarth), dg:get_globalpos()
  local up = vec.unit(vec.sub(pD, pE))
  local s = vec.unit(vec.sub(oapi.get_globalpos(hSun), pD))
  local R = oapi.get_rotationmatrix(hEarth)              -- planet-local -> global; column y = the spin axis
  local axis = vec.unit({ x = R.m12, y = R.m22, z = R.m32 })
  local phi = math.asin(vec.dotp(up, axis))              -- latitude
  local dec = math.asin(vec.dotp(axis, s))               -- the sun's declination
  local east = vec.unit(vec.crossp(up, axis))            -- longitude runs +x -> +z in Orbiter's frame
  local cc = math.cos(phi) * math.cos(dec)
  local kt = (math.sin(-8 * RAD) - math.sin(phi) * math.sin(dec)) / cc
  if kt < -1 or kt > 1 then
    log(string.format('daylight at load (sun %.1f deg) and no night reaches -8 deg at this latitude - left as is', e0 / RAD))
    return
  end
  local k0 = (math.sin(e0) - math.sin(phi) * math.sin(dec)) / cc
  local H0 = math.acos(math.max(-1, math.min(1, k0)))   -- hour angle now, unsigned
  if vec.dotp(east, s) > 0 then H0 = -H0 end            -- sun in the east: morning
  local dH = math.acos(kt) - H0                          -- rotation until the sun sets through -8 deg
  while dH <= 0 do dH = dH + 2 * math.pi end
  local dt = dH / (2 * math.pi) * oapi.get_planetperiod(hEarth) + 2 * 3600
  mjd0 = mjd0 + dt / 86400
  oapi.set_simmjd(mjd0)
  proc.skip()
  nightForced = true
  log(string.format('daylight at load (sun %.1f deg, lat %.1f, dec %.1f) - clock advanced %.2f h to MJD %.4f; sun reads %.1f deg after one frame',
                    e0 / RAD, phi / RAD, dec / RAD, dt / 3600, mjd0, sunElev() / RAD))
end

-- vessel-frame metres (right, forward) -> geographic offset -> lng/lat
local function geo(right, fwd)
  local e = right * math.cos(hdg0) + fwd * math.sin(hdg0)
  local n = fwd * math.cos(hdg0) - right * math.sin(hdg0)
  return dgLng + e / (R0 * math.cos(dgLat)), dgLat + n / R0
end

-- compass heading (rad) from point a to point b, both in vessel-frame metres
local function headingTo(ar, af, br, bf)
  local dr, df = br - ar, bf - af
  local e = dr * math.cos(hdg0) + df * math.sin(hdg0)
  local n = df * math.cos(hdg0) - dr * math.sin(hdg0)
  return math.atan2(e, n)
end

-- ---------------------------------------------------------------------------
-- vessels spawned by the rig
-- ---------------------------------------------------------------------------
local rig = {}      -- name -> { v = interface, h = handle }

-- THE STALE-OBJECT PURGE (a stock Lua interpreter bug, found by the T-key flight of
-- 2026-09-10). Interpreter::lua_pushvessel caches a vessel's Lua object in the registry
-- keyed by its C++ pointer, and the delete hook only strikes the pointer from the validity
-- set (knownVessels) - the registry entry survives. A vessel created after another died is
-- routinely allocated at the freed address, so get_interface hands back the DEAD object and
-- every method on it fails with "Invalid vessel object for self". Detect it, drop the dead
-- registry entry, and fetch again: the interpreter then builds a fresh object.
local function liveVessel(h)
  if h == nil then return nil end
  local v = vessel.get_interface(h)
  if v == nil then return nil end
  if pcall(v.get_name, v) then return v end
  local reg = debug.getregistry()
  for k, val in pairs(reg) do
    if val == v then reg[k] = nil end
  end
  v = vessel.get_interface(h)
  if v ~= nil and pcall(v.get_name, v) then
    log('purged a stale vessel object (interpreter registry) for ' .. v:get_name())
    return v
  end
  return nil
end

local function findVessel(name)
  for i = 0, vessel.get_count() - 1 do
    local v = liveVessel(vessel.get_handle(i))
    if v ~= nil and v:get_name() == name then return v end
  end
  return nil
end

-- create (or re-use a leftover of the same name) and land it at (right, fwd) m from
-- the DG with the given compass heading. arot.x = 10 asks Orbiter to derive the
-- orientation from the heading and the base height from the touchdown points.
local function spawn(name, class, right, fwd, hdg)
  local v = findVessel(name)
  if v == nil or v:get_classname() ~= class then
    if v ~= nil then oapi.del_vessel(name); proc.skip() end
    local h = oapi.create_vessel(name, class, dg:get_rawstatus(1))
    if h == nil then log('could not create ' .. name .. ' (' .. class .. ')'); return nil end
    v = liveVessel(h)
    if v == nil then log('no live interface for ' .. name .. ' (' .. class .. ')'); return nil end
  end
  local lng, lat = geo(right, fwd)
  v:defset_status({ version = 2, status = 1, rbody = hEarth,
                    surf_lng = lng, surf_lat = lat, surf_hdg = hdg,
                    arot = { x = 10, y = 0, z = 0 }, vrot = { x = 0, y = 0, z = 0 } })
  rig[name] = { v = v, h = v:get_handle(), r = right, f = fwd }
  return v
end

local function clearRig()
  for name, _ in pairs(rig) do oapi.del_vessel(name) end
  rig = {}
  proc.skip()
end

-- ---------------------------------------------------------------------------
-- lights
-- ---------------------------------------------------------------------------
-- TINTED WHITES OF EQUAL BRIGHTNESS. In a multi-lamp case a shadow is what its lamp
-- contributed, taken away; the eye weighs red and green as brightness and blue hardly at
-- all, and grass reflects little blue to begin with. Saturated primaries (the two-spot
-- flight) made the red lamp's shadow a dark shape and the blue lamp's invisible. With
-- these every shadow is a luminance drop the eye sees, and the tint says which lamp.
local COL = {
  white  = { r = 1.00, g = 0.96, b = 0.88 },
  warm   = { r = 1.00, g = 0.80, b = 0.50 },
  cool   = { r = 0.50, g = 0.75, b = 1.00 },
  pink   = { r = 1.00, g = 0.62, b = 0.72 },
  mint   = { r = 0.55, g = 1.00, b = 0.65 },
  gold   = { r = 1.00, g = 0.92, b = 0.35 },
  lav    = { r = 0.78, g = 0.66, b = 1.00 },
  peach  = { r = 1.00, g = 0.70, b = 0.55 },
  ice    = { r = 0.70, g = 0.90, b = 1.00 },
}
local BLACK = { r = 0, g = 0, b = 0 }
local SPOT_POS = { x = 0, y = 11.89, z = 0.45 }  -- the floodlight head: lampgen.py's 12 m post
local POST_POS = { x = 0, y = 9.85, z = 0 }      -- the globe

-- a spot lamp at (right, fwd) aimed at the point (tr, tf) at height th; the lamp vessel
-- turns to face it, the emitter tilts down to hit it
local function spotLamp(idx, right, fwd, col, tr, tf, th, prm)
  tr, tf, th = tr or 0, tf or 0, th or 1.5
  local hdg = headingTo(right, fwd, tr, tf)
  local v = spawn(string.format('ORO_LAMP_%02d', idx), 'ORO_LampSpot', right, fwd, hdg)
  if v == nil then return nil end
  local dist = math.sqrt((tr - right) ^ 2 + (tf - fwd) ^ 2)
  local tilt = math.atan2(SPOT_POS.y - th, dist)
  prm = prm or {}
  -- FLAT POOLS: 1/(0.25 + 2e-4 d^2) is 3.7x at 10 m, 1.85x at 38 m, 1.0x at 60 m, 0.66x at
  -- 80 m. With the stock-style 1e-3 constant the ground beside each post ran at 10x in one
  -- saturated colour and drowned the other lamp's 1x there - and its shadow with it (the
  -- two-spot flight). A shadow is legible only where the lamps are comparable, so the
  -- whole field is kept between one and two times full intensity.
  local le = v:add_spotlight(SPOT_POS, { x = 0, y = -math.sin(tilt), z = math.cos(tilt) },
    { range = prm.range or 250, att0 = prm.att0 or 0.25, att1 = 0, att2 = prm.att2 or 2e-4,
      umbra = (prm.umbra or 40) * RAD, penumbra = (prm.penumbra or 60) * RAD },
    col or COL.white, col or COL.white, BLACK)
  le:set_visibility(VIS.ALWAYS)
  le:activate(true)
  return v, le
end

-- the mast: a POINT light at the globe, or (aimed) a spot from the globe
local function postLamp(idx, right, fwd, col, prm, aimAt)
  prm = prm or {}
  local hdg = hdg0
  if aimAt then hdg = headingTo(right, fwd, aimAt.r, aimAt.f) end
  local v = spawn(string.format('ORO_POST_%02d', idx), 'ORO_LampPost', right, fwd, hdg)
  if v == nil then return nil end
  local le
  if aimAt then
    local dist = math.sqrt((aimAt.r - right) ^ 2 + (aimAt.f - fwd) ^ 2)
    local tilt = math.atan2(POST_POS.y - (aimAt.h or 1.5), dist)
    le = v:add_spotlight(POST_POS, { x = 0, y = -math.sin(tilt), z = math.cos(tilt) },
      { range = prm.range or 120, att0 = prm.att0 or 0.25, att1 = 0, att2 = prm.att2 or 3e-4,
        umbra = (prm.umbra or 45) * RAD, penumbra = (prm.penumbra or 180) * RAD },
      col or COL.white, col or COL.white, BLACK)
  else
    le = v:add_pointlight(POST_POS,
      { range = prm.range or 120, att0 = prm.att0 or 0.25, att1 = 0, att2 = prm.att2 or 3e-4 },
      col or COL.white, col or COL.white, BLACK)
  end
  le:set_visibility(VIS.ALWAYS)
  le:activate(true)
  return v, le
end

-- a ring of spot lamps round the DG, all aimed at it: n lamps, radius r, start angle a0.
-- A ring's shadows fall INTO the opposite lamps' pools and read as colour shifts; the cones
-- are opened to 90 deg so no dark gap between pools can pass for a shadow.
local RING = { umbra = 70, penumbra = 90, att2 = 3e-4 }
local function spotRing(n, r, a0, cols, prm)
  prm = prm or RING
  for i = 0, n - 1 do
    local a = (a0 + 360 * i / n) * RAD
    spotLamp(i + 1, r * math.sin(a), r * math.cos(a), cols[(i % #cols) + 1], 0, 0, 1.5, prm)
  end
end

-- a FAN of spot lamps on one side of the DG, all aimed at it: n lamps at radius r spread
-- over `span` degrees centred on bearing `centre` (0 = ahead, -90 = port). Every shadow
-- lands on the far side, on ground every lamp lights, as N crisp rays radiating from the
-- hull, each the colour its own lamp is not - the floodlit-pitch look, and the one that
-- shows N maps as N shadows at a glance.
local FAN = { umbra = 45, penumbra = 65, att2 = 3e-4 }
local function spotFan(n, r, centre, span, cols, prm)
  prm = prm or FAN
  for i = 0, n - 1 do
    local a = (centre - span / 2 + span * i / (n - 1)) * RAD
    spotLamp(i + 1, r * math.sin(a), r * math.cos(a), cols[(i % #cols) + 1], 0, 0, 1.5, prm)
  end
end

-- the DG's own beam: a script-owned copy of its landing light (LightSubsys.cpp values),
-- so the case does not depend on the cockpit switch
local dgBeam = nil
local function dgBeamOn(on)
  if on and dgBeam == nil then
    local tilt = 4 * RAD
    dgBeam = dg:add_spotlight({ x = 0.1, y = -0.3, z = 7.5 }, { x = 0, y = -math.sin(tilt), z = math.cos(tilt) },
      { range = 400, att0 = 1e-3, att1 = 0, att2 = 1.5e-4, umbra = 25 * RAD, penumbra = 40 * RAD },
      COL.white, COL.white, BLACK)
    dgBeam:set_visibility(VIS.ALWAYS)
  end
  if dgBeam ~= nil then dgBeam:activate(on) end
end

-- ---------------------------------------------------------------------------
-- caption
-- ---------------------------------------------------------------------------
local note = oapi.create_annotation()   -- created here, after the reference-vessel check above
note:set_pos(0.015, 0.03, 0.80, 0.46)
note:set_size(0.9)
note:set_colour({ r = 1.0, g = 0.92, b = 0.70 })
local lastText = nil
local function say(text)
  if text ~= lastText then note:set_text(text); lastText = text end
end

local function need(what, ok)
  if ok then return what else return what .. ' <-- NOT SET' end
end

-- ---------------------------------------------------------------------------
-- the camera: track mode round the target; phi is the polar angle from the
-- target's +z (0 = behind it), tht the elevation
-- ---------------------------------------------------------------------------
local CAM_TURNS = 1.15      -- orbits per case: a full turn and a bit, whatever the case length
local cam = { h = hDG, dist = 7.0, tht = 0.30, phi = 1.0, rate = 0.075 }
local function camTarget(h, dist, tht, phi0, rate)
  cam.h = h or hDG; cam.dist = dist or 7.0; cam.tht = tht or 0.30
  cam.phi = phi0 or 1.0; cam.rate = rate or cam.rate      -- the case runner sets the rate from CAM_TURNS
  oapi.set_cameratarget(cam.h, 1)
end
local function camStep(dt)
  cam.phi = cam.phi + cam.rate * dt
  -- Camera::SetRelPos puts the camera at y = sin(tht) * (-distance), so a POSITIVE tht is
  -- below the target (the first flight started under the runway); the cases give the
  -- elevation ABOVE the target and the sign is flipped here, once.
  oapi.set_cameramode({ mode = 'track', trackmode = 'relative', reldist = cam.dist, phi = cam.phi, tht = -cam.tht })
end

-- ---------------------------------------------------------------------------
-- the case runner: sim time paces the case (pause freezes it); T / R are read
-- back as the warp they set and cancelled the same frame
-- ---------------------------------------------------------------------------
local fps = 0
local function hold(dur, textfn)
  local t0 = oapi.get_simtime()
  local tp = oapi.get_simtime()
  local sp = oapi.get_systime()
  while true do
    local t = oapi.get_simtime()
    local left = dur - (t - t0)
    if left <= 0 then return 'next' end
    local ta = oapi.get_tacc()
    if ta > 1.5 then oapi.set_tacc(1); return 'next' end
    if ta < 0.7 then oapi.set_tacc(1); return 'back' end
    local dt = t - tp; tp = t
    local s = oapi.get_systime()
    if s > sp then fps = 0.9 * fps + 0.1 / (s - sp) end
    sp = s
    camStep(dt)
    if textfn then say(textfn(left)) end
    proc.skip()
  end
end

-- single spaces only: the annotation renderer breaks a line at every run of spaces
local KEYS = 'T next / R back / Ctrl+P pause'

-- the client's own instrument, tailed from Orbiter.log: the core opens, appends and closes
-- the file for every line, so the tail is always current. With ShadowDebug at 1 the last
-- "ORO lcl dbg:" line (maps, clusters, fov, range, casters) goes straight into the caption
-- and onto the video; the tester never opens the log. Read once a second.
local dbgLive, dbgNext = nil, 0
local function liveDbg()
  local t = oapi.get_simtime()
  if t < dbgNext then return dbgLive end
  dbgNext = t + 1.0
  local f = io.open('Orbiter.log', 'rb')
  if not f then return dbgLive end
  local size = f:seek('end') or 0
  local back = math.min(size, 16384)
  f:seek('set', size - back)
  local tail = f:read(back) or ''
  f:close()
  local last = nil
  for line in string.gmatch(tail, 'ORO lcl dbg:[^\r\n]*') do last = line end
  if last then dbgLive = last end
  return dbgLive
end
local function resetDbg() dbgLive = nil; dbgNext = 0 end

local function caption(c, left)
  local s = string.format('LIGHTS TEST %d/%d - %s\n', c.n, c.total, c.title)
  s = s .. c.text .. '\n'
  if c.needs then s = s .. 'Needs: ' .. c.needs .. '\n' end
  if c.dbg then
    local live = (S.debug > 0) and liveDbg() or nil
    if live then s = s .. 'Log: ' .. live .. '\n'
    else s = s .. 'Log (ShadowDebug 1): ORO lcl dbg: ' .. c.dbg .. '\n' end
  end
  if c.fps then s = s .. string.format('Frame rate: %.0f fps\n', fps) end
  s = s .. string.format('%s / %d s', KEYS, math.ceil(left))
  return s
end

-- ---------------------------------------------------------------------------
-- the cases
-- ---------------------------------------------------------------------------
local mapsOK  = function(n) return S.shadows ~= 0 and S.maps >= n end
local mapsStr = function(n) return need(n .. ' spot maps (have ' .. S.maps .. ')', mapsOK(n)) end
local cellsStr = function(n) return math.min(n, S.maps) .. '/' .. S.maps .. ' cells' end

local cases = {}

cases[#cases + 1] = { title = 'ONE SPOT', dur = 30,
  text = 'A floodlight 38 m off the port wing, aimed at the DG.\n' ..
         'Expect: a crisp DG shadow on the tarmac stretching away from the lamp;\n' ..
         'the beam pool stays intact on the far side (the far plane is the reach).',
  needs = mapsStr(1),
  dbg = cellsStr(1) .. ', 1 candidates, ' .. atlasName .. ' [0: spot light .. x1 .. cast 1]',
  setup = function() spotLamp(1, -38, 0, COL.white); camTarget(hDG, 8, 0.45, 0.9, 0.075) end }

cases[#cases + 1] = { title = 'THE VESSEL\'S OWN BEAM', dur = 30,
  text = 'The DG\'s landing light on, a ShuttlePB parked 45 m ahead, side-on.\n' ..
         'Expect: the PB casts onto the ground; the DG never darkens its own beam\n' ..
         '(the emitter\'s vessel is excluded from its map - authored-inside-the-hull rule).',
  needs = mapsStr(1),
  dbg = cellsStr(1) .. ', 1 candidates, ' .. atlasName .. ' [0: spot light .. x1 .. cast 1]',
  setup = function()
    spawn('ORO_PB_1', 'ShuttlePB', 0, 45, hdg0 + 90 * RAD)
    dgBeamOn(true)
    camTarget(hDG, 8, 0.32, 2.0, 0.07)
  end,
  teardown = function() dgBeamOn(false) end }

cases[#cases + 1] = { title = 'TWO SPOTS, TWO TINTS', dur = 30,
  text = 'Warm white from port, cool white from starboard, both aimed at the DG.\n' ..
         'Expect: a half-dark, sharp-edged DG shape on EACH side: to starboard in the cool\n' ..
         'pool (the warm lamp\'s shadow), to port in the warm pool (the cool lamp\'s shadow).',
  needs = mapsStr(2),
  dbg = cellsStr(2) .. ', 2 candidates, ' .. atlasName .. ' [0: spot ..][1: spot ..]',
  setup = function() spotLamp(1, -38, 0, COL.warm, 0, 0, 1.5, RING); spotLamp(2, 38, 0, COL.cool, 0, 0, 1.5, RING); camTarget(hDG, 8, 0.45, 0.9, 0.075) end }

cases[#cases + 1] = { title = 'FOUR SPOTS IN A FAN', dur = 30,
  text = 'Warm, cool, pink, mint in a 90 deg fan on the port side, all aimed at the DG.\n' ..
         'Expect: four crisp shadow rays radiating to starboard, each a quarter darker than\n' ..
         'the ground round it and missing its own lamp\'s tint; the four pools overlap there.',
  needs = mapsStr(4),
  dbg = cellsStr(4) .. ', 4 candidates, ' .. atlasName,
  setup = function()
    spotFan(4, 38, -90, 90, { COL.warm, COL.cool, COL.pink, COL.mint })
    camTarget(hDG, 8, 0.45, 1.3, 0.075)
  end }

cases[#cases + 1] = { title = 'SIX SPOTS - THE ATLAS ROW FULL', dur = 30,
  text = 'Six lamps in a 150 deg fan, six tints, all aimed at the DG.\n' ..
         'Expect: six maps in the log; six rays on the HULL and hull-lit objects. The GROUND\n' ..
         'shows ALL SIX (a terrain tile takes its eight strongest lights since 2026-09-19; it took four).',
  needs = mapsStr(6),
  dbg = cellsStr(6) .. ', 6 candidates, ' .. atlasName,
  setup = function()
    spotFan(6, 38, -90, 150, { COL.warm, COL.cool, COL.pink, COL.mint, COL.gold, COL.lav })
    camTarget(hDG, 8, 0.45, 1.3, 0.075)
  end }

cases[#cases + 1] = { title = 'A CLUSTER SHARES ONE MAP', dur = 30,
  text = 'Three white lamps 2.2 m apart on the port side, aimed alike.\n' ..
         'Expect: lights within 3 m aiming within 15 deg share ONE map from their\n' ..
         'centroid - one shadow, slightly softer; the log shows x3 on one light.',
  needs = mapsStr(1),
  dbg = cellsStr(1) .. ', 3 candidates, ' .. atlasName .. ' [0: spot light .. x3 ..]',
  setup = function()
    spotLamp(1, -38, -2.2, COL.white); spotLamp(2, -38, 0, COL.white); spotLamp(3, -38, 2.2, COL.white)
    camTarget(hDG, 8, 0.45, 0.9, 0.075)
  end }

cases[#cases + 1] = { title = 'MORE LIGHTS THAN MAPS', dur = 34,
  text = 'Eight white lamps round the DG at 45 deg, 90 deg cones; only ' .. math.min(S.maps, 8) .. ' can hold a map.\n' ..
         'Expect: the hull keeps ' .. math.min(S.maps, 8) .. ' shadows that must NOT flip as the camera orbits\n' ..
         '(an incumbent loses its map only to a 1.5x stronger challenger); the ground shows all eight.',
  needs = mapsStr(6),
  dbg = cellsStr(8) .. ', 8 candidates, ' .. atlasName,
  setup = function() spotRing(8, 40, 22.5, { COL.white }); camTarget(hDG, 8, 0.34, 0.3, 0.09) end }

-- 2026-09-19: a hemisphere flood cannot be served by ONE perspective map - the caster fit
-- widens back to the full 166 deg cone whenever a base structure sits inside the reach (his
-- flight: fov 166, cast 2), a 24-49 cm texel at 30 m, and the two biases that scale with it
-- lit the ground under the DG's belly. With Point light shadows = Cube and the four extra cells
-- SPARE (no other spot loses its map - a pad full of floods keeps its single maps) the client
-- now gives such a flood the five 93 deg faces round its own axis (the cube a point light gets,
-- with the missing face behind the light) - the case says which of the two it shows.
do
  local cubeFlood = (S.point == 2) and (S.maps >= 5) and (S.shadows ~= 0)
  cases[#cases + 1] = { title = 'THE STADIUM FLOOD', dur = 30,
    text = 'A mast 30 m off, a 180 deg hemisphere flood (the SSV pad\'s light shape).\n' ..
           (cubeFlood
             and ('Expect: a wide pool; the flood casts as a five-face CUBE round its own axis\n' ..
                  '(fov 93 in the log): the DG shadow is crisp and the ground under its belly is\n' ..
                  'dark. One 166 deg map would put a 24-49 cm texel there instead.')
             or  ('Expect: a wide pool; ONE 166 deg map (fov 166 in the log): the DG shadow is\n' ..
                  'coarse and the ground under its belly reads lit - the launch pad look.\n' ..
                  'Point light shadows Cube with 6 maps gives the flood a five-face cube.')),
    needs = cubeFlood and ('Point light shadows Cube, ' .. mapsStr(5)) or mapsStr(1),
    dbg = cubeFlood and ('5/' .. S.maps .. ' cells, 1 candidates, ' .. atlasName .. ' [0: CUBE-spot light .. fov 93 rng 120 ..]')
                     or (cellsStr(1) .. ', 1 candidates, ' .. atlasName .. ' [0: spot light .. fov 166 rng 120 ..]'),
    setup = function() postLamp(1, -30, 0, COL.white, nil, { r = 0, f = 0, h = 1.5 }); camTarget(hDG, 7.5, 0.30, 0.9, 0.075) end }
end

do
  local ptNeed
  if S.point == 2 then ptNeed = 'Point light shadows Cube (have Cube), ' .. mapsStr(5)
  elseif S.point == 1 then ptNeed = 'Point light shadows Aimed (have Aimed), ' .. mapsStr(1)
  else ptNeed = need('Point light shadows Aimed or Cube (have Off)', false) end
  local ptDbg
  if S.point == 2 then ptDbg = '5/' .. S.maps .. ' cells, 1 candidates, ' .. atlasName .. ' [0: CUBE light .. x1 ..]'
  else ptDbg = cellsStr(1) .. ', 1 candidates, ' .. atlasName .. ' [0: aimed light .. x1 ..]' end
  cases[#cases + 1] = { title = 'POINT LIGHT IN A RING OF CASTERS', dur = 34,
    text = 'A 10 m mast with a POINT light, four ShuttlePBs round it at 16 m.\n' ..
           'Expect: radial shadows from all four PBs. Aimed = one map pointed at the\n' ..
           'visible casters; Cube = five faces, the sky face unlit; Off = no shadows.',
    needs = ptNeed, dbg = ptDbg,
    setup = function()
      postLamp(1, 0, 60, COL.white)
      for i = 0, 3 do
        local a = (45 + 90 * i) * RAD
        spawn('ORO_PB_' .. (i + 1), 'ShuttlePB', 16 * math.sin(a), 60 + 16 * math.cos(a), hdg0 + a + 90 * RAD)
      end
      camTarget(rig['ORO_POST_01'].h, 5.0, 0.40, 2.6, 0.08)
    end }
end

cases[#cases + 1] = { title = 'SPOTS RANK BEFORE POINTS', dur = 30,
  text = 'The same mast plus ONE spot lamp on the ring.\n' ..
         'Expect: the spot takes cell 0 first; the point light gets what is left -\n' ..
         'a cube needs five cells (six maps: both fit; four maps: the cube cannot).',
  needs = (S.point == 2) and mapsStr(6) or mapsStr(2),
  dbg = (S.point == 2) and ('6/' .. S.maps .. ' cells, 2 candidates, ' .. atlasName .. ' [0: spot ..][1: CUBE ..]')
                        or (cellsStr(2) .. ', 2 candidates, ' .. atlasName .. ' [0: spot ..][1: aimed ..]'),
  setup = function()
    postLamp(1, 0, 60, COL.white)
    for i = 0, 3 do
      local a = (45 + 90 * i) * RAD
      spawn('ORO_PB_' .. (i + 1), 'ShuttlePB', 16 * math.sin(a), 60 + 16 * math.cos(a), hdg0 + a + 90 * RAD)
    end
    spotLamp(1, -40, 60, COL.warm, 0, 60, 1.5)
    camTarget(rig['ORO_POST_01'].h, 5.0, 0.40, 2.6, 0.08)
  end }

cases[#cases + 1] = { title = 'SIXTEEN LIGHTS', dur = 34, fps = true,
  text = 'Sixteen lamps round the DG at 22.5 deg, eight colours, all on the DG.\n' ..
         'Expect: the hull is LIT AND VISIBLE (the 4096-slot check), no mesh vanishes,\n' ..
         'shadows on the strongest lights; a mesh tests shadows on its 8 strongest, the ground on its 8.',
  needs = need('Local lights 12x/16x (have ' .. (LIGHTCFG[S.lights] or S.lights) .. ')', maxLights >= 12) .. ', ' .. mapsStr(6),
  dbg = cellsStr(16) .. ', 16 candidates, ' .. atlasName,
  setup = function()
    spotRing(16, 42, 11.25, { COL.white, COL.warm, COL.cool, COL.pink, COL.mint, COL.gold, COL.lav, COL.peach },
             { umbra = 70, penumbra = 90, att2 = 4e-4 })
    camTarget(hDG, 8, 0.34, 0.2, 0.09)
  end }

cases[#cases + 1] = { title = 'DAY AND NIGHT', dur = 30,
  text = 'The four-lamp fan again, and the clock jumps twelve hours ahead.\n' ..
         'Expect: vessels AND the terrain keep their spot shadows in daylight, in every Terrain\n' ..
         'shadows mode (the maps have their own terrain sampler since 2026-09-19; Projected used to yield by day).',
  needs = mapsStr(4),
  dbg = cellsStr(4) .. ', 4 candidates, ' .. atlasName,
  setup = function()
    spotFan(4, 38, -90, 90, { COL.warm, COL.cool, COL.pink, COL.mint })
    camTarget(hDG, 8, 0.45, 1.3, 0.075)
    oapi.set_simmjd(mjd0 + 0.5)
  end,
  teardown = function() oapi.set_simmjd(mjd0) end }

-- 2026-09-19 (step 5d, Marg's item 41): THE CROWDED PAD. Three hemisphere floods on the port
-- side, all aimed at the DG - three leaders plus a cube's four extra cells is seven, more than
-- any budget, so no flood can have its cube and every one is the launch pad's case: ONE map
-- each, now CAPPED at the cube's 93-degree face angle round its own axis, with a soft edge
-- over the map's outer tenth so a shadow reaching the cap dissolves instead of cutting. Before
-- the cap each was one 166-degree map (fov 166 in the log wherever a base structure sits in
-- the reach): a half-metre texel at 30 m, the belly lit. The caster fit still narrows inside
-- the cap, so a park with no structure in reach reads a smaller fov than 93 - the tell is the
-- word spot-CAP, not the number.
cases[#cases + 1] = { title = 'THREE FLOODS - THE CROWDED PAD', dur = 30,
  text = 'Three 180 deg hemisphere floods on the port side at 30 m, all aimed at the DG:\n' ..
         'more floods than a cube can be spared for, so each gets ONE map, CAPPED at 93 deg\n' ..
         'round its own axis (spot-CAP in the log). Expect: three crisp DG shadows to\n' ..
         'starboard, each the colour its flood is not, and the ground under the belly dark.\n' ..
         'Past ~46 deg off a flood\'s axis its light casts no shadow, and a shadow reaching\n' ..
         'the cap\'s edge fades over the last tenth. Before the cap: three coarse 166 deg maps.',
  needs = mapsStr(3),
  dbg = cellsStr(3) .. ', 3 candidates, ' .. atlasName .. ' [0: spot-CAP light .. fov <=93 rng 120 ..][1: spot-CAP ..][2: spot-CAP ..]',
  setup = function()
    postLamp(1, -30, 0, COL.white, nil, { r = 0, f = 0, h = 1.5 })
    postLamp(2, -23, 19, COL.warm, nil, { r = 0, f = 0, h = 1.5 })
    postLamp(3, -23, -19, COL.cool, nil, { r = 0, f = 0, h = 1.5 })
    camTarget(hDG, 7.5, 0.30, 0.9, 0.075)
  end }

for i, c in ipairs(cases) do c.n = i; c.total = #cases end

-- ---------------------------------------------------------------------------
-- run
-- ---------------------------------------------------------------------------
local function titleCard()
  local w = {}
  if not cfgFound then w[#w + 1] = 'D3D9Client.cfg not found in the Orbiter root - settings unknown' end
  if S.shadows == 0 then w[#w + 1] = 'Spot light shadows are OFF - every shadow case will show none' end
  if S.maps < 6 and S.shadows ~= 0 then w[#w + 1] = 'cases 5, 7, 8, 10, 11 want 6 spot maps (have ' .. S.maps .. ')' end
  if S.point == 0 then w[#w + 1] = 'Point light shadows OFF - case 9 will show none' end
  if S.point ~= 2 and S.shadows ~= 0 then w[#w + 1] = 'Point light shadows not Cube - case 8\'s flood stays one coarse 166 deg map' end
  if maxLights < 12 then w[#w + 1] = 'case 11 wants 12x or 16x local lights (have ' .. (LIGHTCFG[S.lights] or S.lights) .. ')' end
  if S.terrain ~= 3 then w[#w + 1] = 'Terrain shadows not Cascaded - spot maps use the local atlas (the terrain reads it day and night since 2026-09-19)' end
  if S.debug == 0 then w[#w + 1] = 'ShadowDebug = 0 - set 1 in D3D9Client.cfg for the ORO lcl dbg log line' end
  if nightForced then w[#w + 1] = 'the scenario was in daylight - the clock was advanced to two hours after sunset' end
  local s = 'ORO LIGHTS TEST RIG\n' ..
    string.format('Local lights: %s / Spot light shadows: %s\n', LIGHTCFG[S.lights] or tostring(S.lights),
                  (S.shadows == 0) and 'Off' or (S.maps .. ' spot maps')) ..
    string.format('Point light shadows: %s / Terrain shadows: %s\n', PTMODE[S.point] or tostring(S.point),
                  TERRSHD[S.terrain] or tostring(S.terrain)) ..
    string.format('Vessel self-shadows: %s / ShadowDebug: %d\n', SELFSHD[S.selfshd] or tostring(S.selfshd), S.debug)
  for _, line in ipairs(w) do s = s .. 'WARN: ' .. line .. '\n' end
  s = s .. string.format('%d cases, about %d s each, the camera orbits each one. %s', #cases, 31, KEYS)
  log('settings: lights ' .. tostring(S.lights) .. ' shadows ' .. tostring(S.shadows) .. ' maps ' .. tostring(S.maps) ..
      ' point ' .. tostring(S.point) .. ' terrain ' .. tostring(S.terrain) .. ' selfshd ' .. tostring(S.selfshd) .. ' debug ' .. tostring(S.debug))
  for _, line in ipairs(w) do log('WARN ' .. line) end
  return s
end

local function main()
  oapi.set_tacc(1)
  camTarget(hDG, 7, 0.30, 0.9, 0.05)
  clearRig()
  forceNight()
  local first = titleCard()
  cam.rate = 0.35 * 2 * math.pi / 12
  local key = hold(12, function(left) return first .. string.format(' / %d s', math.ceil(left)) end)
  local i = 1
  while i >= 1 and i <= #cases do
    local c = cases[i]
    log(string.format('case %d/%d - %s', c.n, c.total, c.title))
    c.setup()
    cam.rate = CAM_TURNS * 2 * math.pi / c.dur
    resetDbg()
    proc.skip()
    local r = hold(c.dur, function(left) return caption(c, left) end)
    if c.teardown then c.teardown() end
    clearRig()
    if r == 'back' then i = i - 1 else i = i + 1 end
    if i < 1 then i = 1 end
  end
  oapi.set_simmjd(mjd0)
  dgBeamOn(false)
  camTarget(hDG, 7, 0.30, cam.phi, 0.0)
  hold(8, function(left) return 'LIGHTS TEST - done. Everything the rig spawned is deleted; the DG is yours.\n' ..
                                 'Report: your settings from the title card, the video or unpaused screenshots,\n' ..
                                 'and Orbiter.log (ORO lcl dbg lines if ShadowDebug was 1).' end)
end

local ok, err = pcall(main)
if not ok then
  if err == nil then
    -- the interpreter unwinds a running script with a nil error when the session closes
    log('interrupted - session closing')
  else
    log('ERROR ' .. tostring(err))
    say('LIGHTS TEST - error: ' .. tostring(err))
    pcall(clearRig)
    pcall(function() oapi.set_simmjd(mjd0) end)
    pcall(proc.wait_simdt, 10)
  end
end
pcall(function() oapi.del_annotation(note) end)
log('finished')
